# Generated by Django 5.2.10 on 2026-01-31 06:31

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('filled_data', models.JSONField(default=dict)),
                ('pdf_file', models.FileField(upload_to='generated_pdfs/')),
                ('file_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_pdfs', to='appointments.appointment')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_pdfs', to=settings.AUTH_USER_MODEL)),
                ('generated_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_pdfs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Generated PDF',
                'verbose_name_plural': 'Generated PDFs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('prescription', 'Prescription'), ('report', 'Medical Report'), ('lab_result', 'Lab Result'), ('imaging', 'Imaging/X-Ray'), ('insurance', 'Insurance Document'), ('id_proof', 'ID Proof'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='patient_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_pdf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pdf_system.generatedpdf')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PDFTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('template_type', models.CharField(choices=[('prescription', 'Prescription'), ('medical_report', 'Medical Report'), ('discharge_summary', 'Discharge Summary'), ('lab_report', 'Lab Report'), ('certificate', 'Medical Certificate'), ('invoice', 'Invoice'), ('referral', 'Referral Letter'), ('consent_form', 'Consent Form'), ('custom', 'Custom')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('header_content', ckeditor.fields.RichTextField(blank=True, help_text='Header section of PDF', null=True)),
                ('body_content', ckeditor.fields.RichTextField(help_text='Main content with placeholders like {{patient_name}}')),
                ('footer_content', ckeditor.fields.RichTextField(blank=True, help_text='Footer section of PDF', null=True)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='pdf_templates/headers/')),
                ('footer_image', models.ImageField(blank=True, null=True, upload_to='pdf_templates/footers/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='pdf_templates/logos/')),
                ('page_size', models.CharField(choices=[('A4', 'A4'), ('Letter', 'Letter'), ('Legal', 'Legal')], default='A4', max_length=20)),
                ('orientation', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', max_length=20)),
                ('margin_top', models.PositiveIntegerField(default=50)),
                ('margin_bottom', models.PositiveIntegerField(default=50)),
                ('margin_left', models.PositiveIntegerField(default=50)),
                ('margin_right', models.PositiveIntegerField(default=50)),
                ('dynamic_fields', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='generatedpdf',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_pdfs', to='pdf_system.pdftemplate'),
        ),
    ]
